run:
   timeout: 5m
   tests: false
   modules-download-mode: readonly
output:
   formats:
   - format: colored-line-number
   sort-results: true
linters:
   disable-all: true
   enable:
   - errcheck
   - gosimple
   - govet
   - gosec
   - goimports
   - ineffassign
   - staticcheck
   - unused
linters-settings:
   goimports:
     local-prefixes: github.com/openshift/lightspeed-operator
issues:
   exclude-dirs:
     - test/