version: "2"                          # ← mandatory for v2.x

run:
    timeout: 5m
    tests: false
    modules-download-mode: readonly

output:
    formats:
        colored-line-number:
            path: stdout
    sort-results: true

llinters:
    default: none
    enable:
    - errcheck
    - gosimple
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused

formatters:
    enable:
    - goimports                 # <-- moved here
    settings:
        goimports:
            local-prefixes: github.com/openshift/lightspeed-operator

linters-settings:
    goimports:
        local-prefixes: github.com/openshift/lightspeed-operator

issues:
    exclude-dirs:
    - test/