# The images are pulled from our redhat-user-workloads registry or staging registry while the production image is not yet available.
kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
  name: openshift-lightspeed-prod-to-ci
spec:
  imageDigestMirrors:
    - source: registry.redhat.io/openshift-lightspeed/lightspeed-rhel9-operator
      mirrors:
        - registry.staging.redhat.io/openshift-lightspeed-tech-preview/lightspeed-rhel9-operator
        - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-operator
    - source: registry.redhat.io/openshift-lightspeed/lightspeed-operator-bundle
      mirrors:
        - registry.staging.redhat.io/openshift-lightspeed-tech-preview/lightspeed-operator-bundle
        - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/bundle
    - source: registry.redhat.io/openshift-lightspeed/lightspeed-service-api-rhel9
      mirrors:
        - registry.staging.redhat.io/openshift-lightspeed-tech-preview/lightspeed-service-api-rhel9
        - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-service
    - source: registry.redhat.io/openshift-lightspeed/lightspeed-console-plugin-rhel9
      mirrors:
        - registry.staging.redhat.io/openshift-lightspeed-tech-preview/lightspeed-console-plugin-rhel9
        - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-console
