resources:
- manager.yaml
- imagedigestmirrorset.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:049a1a398ed87e4f35c99b36304055c7f75d0188a4d8c1726df59b5f400561e5
  name: controller
  newName: registry.redhat.io/openshift-lightspeed-beta/lightspeed-rhel9-operator
