resources:
- manager.yaml
- imagedigestmirrorset.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:f395c217c9cb67205edc7061bdb5ae52e30c2c934c40f558b0403a9f0f4c96e5
  name: controller
  newName: registry.redhat.io/openshift-lightspeed-tech-preview/lightspeed-rhel9-operator
