apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: service-account
    app.kubernetes.io/part-of: lightspeed-operator
  name: lightspeed-operator-metrics-reader
