apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: lightspeed-operator
  name: lightspeed-operator-prometheus-operator
rules:
- apiGroups:
  - ""
  resourceNames:
  - lightspeed-operator-metrics-reader-token
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
