apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: lightspeed-operator
  name: lightspeed-operator-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lightspeed-operator-prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: openshift-monitoring
