apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: update-bundle-related-images-run-1
  namespace: crt-nshift-lightspeed-tenant
  description: |
    This pipeline run simulates a pipeline run triggered by Konflux.
    These 3 parameters are passed by Konflux: snapshot, release and releasePlan. 
    Other parameters are set by the release plan.
spec:
  serviceAccountName: release-bot
  pipelineRef:
    params:
      - name: url
        value: https://github.com:openshift/lightspeed-operator.git
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/release/bundle-update/pipeline.yaml
    resolver: git
  params:
    - name: snapshot
      value: "crt-nshift-lightspeed-tenant/ols-dsz4g"
    - name: release
      value: "crt-nshift-lightspeed-tenant/ga-1.0.0-1"
    - name: releasePlan
      value: "crt-nshift-lightspeed-tenant/ols-release-plan"
