apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: metrics-reader-token
  namespace: openshift-lightspeed
  annotations:
    kubernetes.io/service-account.name: metrics-reader
  labels:
    app.kubernetes.io/name: service-account-token
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: lightspeed-operator
