apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: openshift-lightspeed
  labels:
    app.kubernetes.io/name: service-account
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: lightspeed-operator