apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: llm-api-keys
        type: openai
        models:
          - name: merlinite-7b-lab-Q4_K_M
        name: instructlab
        url: https://instructlab.mydomain.io
  ols:
    defaultModel: merlinite-7b-lab-Q4_K_M
    defaultProvider: instructlab
    logLevel: INFO
    tlsConfig:
      keyCertSecretRef:
        name: tls-secret-name
    deployment:
      replicas: 1
      console:
        caCertificate: |
          -----BEGIN CERTIFICATE-----
          your-certificate content, syntax sensitive
          -----END CERTIFICATE-----
