kind: Kustomization
# this generates Konflux release objects for OpenShift Lightspeed
# run `make konflux-release` to generate the Konflux resources in release-konflux/
# Release notes should be updated in the release objects, refer to https://konflux.pages.redhat.com/docs/users/releasing/releasing-with-an-advisory.html


# channel
namePrefix: stable-
# version
nameSuffix: -1.0.2-2

resources:
  - base/components.yaml
  - base/bundle.yaml
  - base/fbc-prod-v4-15.yaml
  - base/fbc-prod-v4-16.yaml
  - base/fbc-prod-v4-17.yaml
  - base/fbc-prod-v4-18.yaml
  - base/fbc-prod-v4-19.yaml
  - base/fbc-staging.yaml

patches:
  - target:
      kind: Release
      name: ols
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-4rx25
  - target:
      kind: Release
      name: ols-bundle
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-bundle-n7m85
  - target:
      kind: Release
      name: fbc-prod-415
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-15-b9tkf
  - target:
      kind: Release
      name: fbc-prod-416
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-16-tmzj6
  - target:
      kind: Release
      name: fbc-prod-417
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-17-ljpz4
  - target:
      kind: Release
      name: fbc-prod-418
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-18-kskxx
  - target:
      kind: Release
      name: fbc-prod-419
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-19-qqv2l
  - target:
      kind: Release
      name: fbc-staging
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-19-tprz2
