kind: Kustomization
# this generates Konflux release objects for OpenShift Lightspeed
# run `make konflux-release` to generate the Konflux resources in release-konflux/
# Release notes should be updated in the release objects, refer to https://konflux.pages.redhat.com/docs/users/releasing/releasing-with-an-advisory.html


# channel
namePrefix: tech-preview-
# version
nameSuffix: -0.3.6-1

resources:
  - base/components.yaml
  - base/bundle.yaml
  - base/fbc-prod-v4-15.yaml
  - base/fbc-prod-v4-16.yaml
  - base/fbc-prod-v4-17.yaml
  - base/fbc-prod-v4-18.yaml
  - base/fbc-staging.yaml

patches:
  - target:
      kind: Release
      name: ols
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-vd4zh
  - target:
      kind: Release
      name: ols-bundle
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-bundle-4fsfb
  - target:
      kind: Release
      name: fbc-prod-415
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-15-vmvfr
  - target:
      kind: Release
      name: fbc-prod-416
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-16-98q76
  - target:
      kind: Release
      name: fbc-prod-417
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-17-hs4ws
  - target:
      kind: Release
      name: fbc-prod-418
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-18-9xkj5
  - target:
      kind: Release
      name: fbc-staging
    patch: |-
      - op: replace
        path: /spec/snapshot
        value: ols-fbc-v4-18-9xkj5
