apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: ols-installer
spec:
  params:
    - name: test-name
      type: string
    - name: ocp-login-command
      type: string
      description: ""
  steps:
    - name: install
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      env:
        - name: TEST_NAME
          value: $(params.test-name)
      script: |
        #!/bin/sh
        echo $(params.ocp-login-command)
        $(params.ocp-login-command)

        echo "ols is installing"
        #operator-sdk run bundle quay.io/lightspeed/lightspeed-operator:latest --namespace openshift-operators --skpit-tls --timeout 5m0s