apiVersion: v1
kind: Secret
metadata:
  name: release-bot-github-token
  namespace: crt-nshift-lightspeed-tenant
type: Opaque
stringData:
  github-token: <Github classic token used by release bot service account, able to open PRs to the operator repo>